config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invitations
  mount Pwa::Engine, at: ''

  constraints subdomain: '' do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
    resources :games, path: 'app', except: [:edit] do
      resources :invitations, only: [:show, :new, :create]
      resources :participants, except: [:edit, :update, :destroy] do
        resources :tips, except: [:show, :new, :edit]
        resources :tips, only: [:new, :edit], constraints: Modalist::Ajax.new
      end
      resources :matches, only: [:index, :show]
      resources :nations, only: [:show]
    end
    root to: 'welcome#index'
  end

  match '*path', to: 'r404#not_found', via: :all
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  belongs_to :user
  has_many :participants, dependent: :destroy
  has_many :invitations, dependent: :destroy

  validates :name, presence: true
  validates :rule_match, numericality: true
  validates :rule_goal_difference, numericality: true
  validates :rule_tendency, numericality: true
  validates :rule_miss, numericality: true

  scope :personal, -> { where(private: true) }
  scope :shared, -> { where(private: false) }
  scope :sorted, lambda { |user|
    includes(:participants).sort_by do |game|
      game.participants.find_by(user_id: user.id)
          .days_left_before_next_required_tip
    end
  }
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_game, only: [:show, :update, :destroy]

  layout 'app'

  def index
    @games = current_user.games.sorted(current_user)
    @invitations = current_user.invitations.unaccepted
    authorizes! :read, @games
    authorizes! :update, @invitations
    turbolinks_animate 'fadein'
    render layout: 'application'
  end

  def show
    authorize! :read, @game
    @participants = @game.participants.leaderboard.take(3)
    authorizes! :read, @participants
    @current_matches = Match.live.order(:begins_at)
    @next_matches = Match.future.limit(3).order(:begins_at)
    authorizes! :read, @current_matches
    authorizes! :read, @next_matches
    turbolinks_animate 'fadein'
  end

  def new
    @game = current_user.administrating_games.build
    authorize! :create, @game
    turbolinks_animate 'fadeinright'
    render layout: 'back'
  end

  def create
    @game = current_user.administrating_games.build game_params
    authorize! :create, @game

    if @game.save
      redirect_to new_game_participant_url(game_id: @game.to_param),
                  notice: I18n.t('games.create.success')
    else
      redirect_to new_game_url, alert: I18n.t('games.create.error')
    end
  end

  def update
    authorize! :update, @game

    if @game.update game_params
      redirect_to @game, notice: I18n.t('games.update.success')
    else
      redirect_to @game, alert: I18n.t('games.update.error')
    end
  end

  def destroy
    authorize! :destroy, @game
    @game.destroy
    redirect_to games_url, notice: I18n.t('games.destroy.success')
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :bet, :rule_match,
                                 :rule_goal_difference, :rule_tendency,
                                 :rule_miss, :private)
  end
end

app/views/games/_form.html.haml
= simple_form_for game do
  = component 'myg/form-field', as: :input, attribute: :name, class_name: 'game', label: t('games._form.name'), input_html: { required: true, value: game.name, autofocus: true }

  %h3 Rules
  = component 'myg/form-field', as: :input, attribute: :rule_match, class_name: 'game', label: [t('games._form.rule_match.title'), t('games._form.rule_match.content')], input_html: { value: game.rule_match, type: :number, placeholder: '5' }
  = component 'myg/form-field', as: :input, attribute: :rule_goal_difference, class_name: 'game', label: [t('games._form.rule_goal_difference.title'), t('games._form.rule_goal_difference.content')], input_html: { value: game.rule_goal_difference, type: :number, placeholder: '3' }
  = component 'myg/form-field', as: :input, attribute: :rule_tendency, class_name: 'game', label: [t('games._form.rule_tendency.title'), t('games._form.rule_tendency.content')], input_html: { value: game.rule_tendency, type: :number, placeholder: '2' }
  = component 'myg/form-field', as: :input, attribute: :rule_miss, class_name: 'game', label: [t('games._form.rule_miss.title'), t('games._form.rule_miss.content')], input_html: { value: game.rule_miss, type: :number, placeholder: '0' }

  %h3 More...
  = component 'myg/form-field', as: :input, attribute: :bet, class_name: 'game', label: [t('d.bet'), t('games._form.bet')], input_html: { value: game.bet, placeholder: t('games._form.bet_placeholder') }
  = component 'myg/form-field', as: :switch, attribute: :private, class_name: 'game', inline_label: [t('d.private'), t('games._form.private')], input_html: { checked: game.private }

  .myg-button__container.myg-grid__flex.-reverse
    = component 'myg/button', value: t('games._form.submit')

app/views/games/_game.html.haml
= link_to game, class: 'game' do
  .myg-card
    %h4= game.name
    %p.sm
      - if game.participants.find_by(user_id: current_user.id).days_left_before_next_required_tip == Float::INFINITY
        = t('games._game.next_required_tip.none')
      - else
        %span= pluralize(game.participants.find_by(user_id: current_user.id).days_left_before_next_required_tip, t('games._game.next_required_tip.day'), t('games._game.next_required_tip.days'))
        = t('games._game.next_required_tip.some')
    %p.sm= t('games._game.leaderboard', place: game.participants.find_by(user_id: current_user.id).position.ordinalize, of: game.participants.count)

app/views/games/index.html.haml
- meta title: t('d.overview')

%h1= t('games.index.hi', name: current_user.name)

.myg-card__container
  - @games&.each do |game|
    = render game
  = link_to new_game_url, class: 'card' do
    .myg-card
      %h4= t('games.index.new.title')
      %p.sm= t('games.index.new.content')

%h3= t('d.invitations')
- if @invitations.any?
  .myg-card__container
    - @invitations&.each do |invitation|
      = render invitation
- else
  %p= t('games.index.no_invitations')

%h3= t('d.account')
.myg-button__container.myg-grid__flex
  = link_to t('d.settings'), edit_user_registration_url, class: 'myg-button--secondary'
  = link_to t('d.signout'), destroy_user_session_url, method: :delete, class: 'myg-button--secondary -error'

app/views/games/new.html.haml
- meta title: t('games.new.title')

%h1.sm= t('games.new.title')

= render 'form', game: @game

app/views/games/show.html.haml
- meta title: t('games.show.title', name: @game.name)

= link_to t('games.show.all_games'), games_url, class: 'myg-text__hyperlink -inherit'
%h1.sm= @game.name

- if current_user.nil?
  .join
    %h2= t('games.show.join.title')
    %p= t('games.show.join.content')
    = link_to t('games.show.join.submit'), new_user_registration_url(game_id: @game.to_param), class: 'myg-button--light'
    %p.sm= t('games.show.rules.bet', bet: @game.bet || t('d.none'))
- elsif current_user.participants.find_by(game: @game).nil?
  .join
    %h2= t('games.show.join.title')
    %p= t('games.show.join.content')
    = link_to t('games.show.join.submit'), new_game_participant_url(game_id: @game.to_param), class: 'myg-button--light'
    %p.sm= t('games.show.rules.bet', bet: @game.bet || t('d.none'))

%h3= t('d.leaderboard')
.myg-card__container
  - @participants.each do |participant|
    = render participant
  = link_to t('games.show.full_leaderboard'), game_participants_url(game_id: @game.to_param), class: 'myg-text__hyperlink -inherit', data: { turbolinks_animate_type: 'nav' }

- if @current_matches.any?
  %h3= t('games.show.current_matches')
  .myg-card__container
    - @current_matches.each do |match|
      = render match, game: @game
    = link_to t('games.show.browse_matches'), game_matches_url(game_id: @game.to_param, anchor: Match.next&.id), class: 'myg-text__hyperlink -inherit', data: { turbolinks_animate_type: 'nav' }

- if @next_matches.any?
  %h3= t('games.show.next_matches')
  .myg-card__container
    - @next_matches.each do |match|
      = render match, game: @game
    = link_to t('games.show.browse_matches'), game_matches_url(game_id: @game.to_param, anchor: Match.next&.id), class: 'myg-text__hyperlink -inherit', data: { turbolinks_animate_type: 'nav' }

%h3= t('d.rules')
.myg-list--contained
  .myg-list__item= t('games.show.rules.bet', bet: @game.bet || t('d.none'))
  .myg-list__item= t('games.show.rules.match', rule_match: @game.rule_match)
  .myg-list__item= t('games.show.rules.goal_difference', rule_goal_difference: @game.rule_goal_difference)
  .myg-list__item= t('games.show.rules.tendency', rule_tendency: @game.rule_tendency)
  .myg-list__item= t('games.show.rules.miss', rule_miss: @game.rule_miss)
%p.sm= t('games.show.rules.penalties')

- if can? :update, @game
  %h3= t('d.manage')
  .myg-button__container.myg-grid__flex
    = link_to t('games.show.invite'), new_game_invitation_url(game_id: @game.to_param), class: 'myg-button'
    = link_to t('d.delete'), game_url(id: @game.to_param), method: :delete, class: 'myg-button--secondary -error', data: { confirm: t('d.are_you_sure') }