config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invitations
  mount Pwa::Engine, at: ''

  constraints subdomain: '' do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
    resources :games, path: 'app', except: [:edit] do
      resources :invitations, only: [:show, :new, :create]
      resources :participants, except: [:edit, :update, :destroy] do
        resources :tips, except: [:show, :new, :edit]
        resources :tips, only: [:new, :edit], constraints: Modalist::Ajax.new
      end
      resources :matches, only: [:index, :show]
      resources :nations, only: [:show]
    end
    root to: 'welcome#index'
  end

  match '*path', to: 'r404#not_found', via: :all
end

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  notification_object

  belongs_to :home, class_name: 'Nation'
  belongs_to :away, class_name: 'Nation'
  has_many :tips, dependent: :destroy

  validates :begins_at, presence: true

  scope :live, -> { past.where(finished: false) }
  scope :past, lambda {
    where('begins_at < ?', Time.now.strftime('%Y-%m-%d %H:%M:%S'))
  }
  scope :future, lambda {
    where('begins_at >= ?', Time.now.strftime('%Y-%m-%d %H:%M:%S'))
  }
  scope :soon, lambda {
    future.where('begins_at < ?', Date.tomorrow.strftime('%Y-%m-%d %H:%M:%S'))
  }

  def self.next
    future.first
  end

  def live?
    home_goals && away_goals && !finished
  end

  def goals_available?
    home_goals && away_goals
  end

  def penalties?
    home_penalties && away_penalties
  end

  def goal_difference
    pure_goal_difference.abs
  end

  def pure_goal_difference
    home_goals - away_goals
  end

  def penalty_pure_goal_difference
    home_penalties - away_penalties
  end

  def count_tips_by_others(participant)
    tips.includes(:participant)
        .where(participants: { game_id: participant.game_id })
        .where.not(participants: { id: participant.id }).count
  end
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

class MatchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game
  before_action :set_match, only: [:show]

  layout 'app'

  def index
    @matches = Match.all.order(:begins_at)
    authorizes! :read, @matches
    turbolinks_animate 'fadein'
  end

  def show
    authorize! :read, @match
    @tips = @match.tips.includes(:participant)
                  .where(participants: { game: @game })
                  .sort_by(&:earned_points).reverse
    turbolinks_animate 'fadeinright'
    render layout: 'back'
  end

  private

  def set_game
    @game = Game.find(params[:game_id])
    authorize! :read, @game
  end

  def set_match
    @match = Match.find(params[:id])
  end
end

app/views/matches/_match.html.haml
= link_to game_match_url(game_id: game.to_param, id: match.to_param), class: 'match', id: match.id, data: { turbolinks_animate_animation: 'fadeout' } do
  .myg-card
    .match-wrapper{ class: ('live' if match.live?) }
      %p.sm= match.home.name
      %h4
        = match.home_penalties || match.home_goals || '-'
        = ':'
        = match.away_penalties || match.away_goals || '-'
      %p.sm= match.away.name
    .tip-wrapper
      = component 'flag', nation: match.home, size: 'tn'
      %p.sm
        = current_user ? Tip.includes(:participant).find_by(match_id: match.id, participants: { game: game, user: current_user })&.home_goals || '?' : '?'
        = ':'
        = current_user ? Tip.includes(:participant).find_by(match_id: match.id, participants: { game: game, user: current_user })&.away_goals || '?' : '?'
      = component 'flag', nation: match.away, size: 'tn'
    %p.sm
      - if current_user&.participants&.find_by(game: game)
        = t('matches._match.tips_by_others.content', n_participants: pluralize(match.count_tips_by_others(current_user.participants.find_by(game: game)), t('matches._match.tips_by_others.other_person'), t('matches._match.tips_by_others.others')))
        ·
      = l(match.begins_at)

app/views/matches/_tip.html.haml
= link_to game_participant_url(game_id: tip.participant.game.to_param, id: tip.participant.to_param), class: 'match-tip', data: { turbolinks_animate_animation: 'fadeout' } do
  - if tip.match.begins_at.future?
    .myg-card
      %p.sm= '-'
      %h4= tip.participant.user.name
      %p.sm= tip.participant.earned_points
      %p.sm
        - if tip.participant.user == current_user
          = tip.home_goals
          = ':'
          = tip.away_goals
        - else
          = '? : ?'
  - else
    .myg-card{ class: "p#{tip_class(tip)}" }
      %p.sm= "#{'+' if tip.earned_points.positive?}#{tip.earned_points}"
      %h4= tip.participant.user.name
      %p.sm= tip.participant.earned_points
      %p.sm
        = tip.home_goals
        = ':'
        = tip.away_goals

app/views/matches/index.html.haml
- meta title: t('matches.index.title', name: @game.name)

%h1= t('d.matches')

- @matches.group_by { |match| match.begins_at.to_date }.each do |date, match|
  %p= l(date)
  .myg-card__container
    = render match, game: @game

app/views/matches/show.html.haml
- meta title: t('matches.show.title', home: @match.home.name, away: @match.away.name)
- replace :back_location, game_matches_url(game_id: @game.to_param, anchor: @match.id)

.match-wrapper{ class: ('live' if @match.live?) }
  .result-wrapper
    = link_to game_nation_url(game_id: @game.to_param, id: @match.home.to_param), class: 'nation-wrapper', data: { turbolinks_animate_animation: 'fadeout' } do
      = component 'flag', nation: @match.home
      %h4= @match.home.name
    %h1.sm
      = @match.home_penalties || @match.home_goals || '-'
      = ':'
      = @match.away_penalties || @match.away_goals || '-'
    = link_to game_nation_url(game_id: @game.to_param, id: @match.away.to_param), class: 'nation-wrapper', data: { turbolinks_animate_animation: 'fadeout' } do
      = component 'flag', nation: @match.away
      %h4= @match.away.name
  %p.sm
    %span.live= t('matches.show.live')
    = @match.begins_at.future? ? t('matches.show.match_starts_on') : t('matches.show.match_started_on')
    = l(@match.begins_at)

.content-wrapper
  %h3= t('d.tips')
  - if @tips.any?
    .myg-card__container
      - @tips.each do |tip|
        = render 'tip', tip: tip
  - else
    %p= t('matches.show.no_tips')

  - if Tip.includes(:participant).find_by(match_id: @match.id, participants: { game: @game, user: current_user }).nil?
    .myg-button__container.myg-grid__flex.-reverse
      = link_to t('matches.show.tip_this_match'), new_game_participant_tip_url(game_id: @game.to_param, participant_id: @game.participants.find_by(user_id: current_user.id).to_param, match_id: @match.to_param), class: 'modalist--trigger myg-button'
  - elsif @match.begins_at.future?
    .myg-button__container.myg-grid__flex.-reverse
      = link_to t('matches.show.edit_your_tip'), edit_game_participant_tip_url(game_id: @game.to_param, participant_id: @game.participants.find_by(user_id: current_user.id).to_param, id: Tip.includes(:participant).find_by(match_id: @match.id, participants: { game: @game, user: current_user }).to_param), class: 'modalist--trigger myg-button'