config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invitations
  mount Pwa::Engine, at: ''

  constraints subdomain: '' do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
    resources :games, path: 'app', except: [:edit] do
      resources :invitations, only: [:show, :new, :create]
      resources :participants, except: [:edit, :update, :destroy] do
        resources :tips, except: [:show, :new, :edit]
        resources :tips, only: [:new, :edit], constraints: Modalist::Ajax.new
      end
      resources :matches, only: [:index, :show]
      resources :nations, only: [:show]
    end
    root to: 'welcome#index'
  end

  match '*path', to: 'r404#not_found', via: :all
end

app/models/tip.rb
# frozen_string_literal: true

class Tip < ApplicationRecord
  before_save :check_if_match_started
  before_create :check_if_already_tipped

  belongs_to :participant
  belongs_to :match

  validates :home_goals, presence: true
  validates :away_goals, presence: true

  scope :unchangeable, lambda {
    includes(:match)
      .where('matches.begins_at < ?', Time.now.strftime('%Y-%m-%d %H:%M:%S'))
  }

  delegate :game, to: :participant, allow_nil: true

  def goal_difference
    pure_goal_difference.abs
  end

  def pure_goal_difference
    home_goals - away_goals
  end

  def earned_points
    return 0 unless match.goals_available?

    return game.rule_match if match?
    return game.rule_goal_difference if goal_difference?
    return game.rule_tendency if tendency?

    game.rule_miss
  end

  def match?
    return false if match.penalties?

    home_goals == match.home_goals && away_goals == match.away_goals
  end

  def goal_difference?
    return false if match.penalties?

    tendency? && goal_difference == match.goal_difference
  end

  def tendency?
    return tendency_penalties? if match.penalties?

    Tendency.new(pure_goal_difference, match.pure_goal_difference).perform
  end

  def tendency_penalties?
    Tendency.new(pure_goal_difference, match.penalty_pure_goal_difference)
            .perform
  end

  private

  def check_if_match_started
    return unless match.begins_at.past?

    throw(:abort)
  end

  def check_if_already_tipped
    return unless match.tips.where(participant_id: participant.id).any?

    throw(:abort)
  end
end

app/controllers/tips_controller.rb
# frozen_string_literal: true

class TipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game
  before_action :set_participant
  before_action :set_tip, only: [:edit, :update, :destroy]

  layout 'app'

  def index
    @matches_grouped_by_day = Match.future.order(:begins_at).group_by do |match|
      match.begins_at.to_date
    end
    authorizes! :read, @matches
    turbolinks_animate 'fadein'
  end

  def new
    @tip = @participant.tips.build match: Match.find(params[:match_id])
    authorize! :create, @tip
    modalist
  end

  def edit
    authorize! :update, @tip
    modalist
  end

  def create
    @tip = @participant.tips.build tip_params

    if @tip.save
      redirect_to game_participant_tips_url(
        game_id: @game.to_param, participant_id: @participant.to_param
      ), notice: I18n.t('tips.create.success')
    else
      redirect_to game_participant_tips_url(
        game_id: @game.to_param, participant_id: @participant.to_param
      ), notice: I18n.t('tips.create.error')
    end
  end

  def update
    authorize! :update, @tip

    if @tip.update tip_params
      redirect_to game_participant_tips_url(
        game_id: @game.to_param, participant_id: @participant.to_param
      ), notice: I18n.t('tips.update.success')
    else
      redirect_to game_participant_tips_url(
        game_id: @game.to_param, participant_id: @participant.to_param
      ), notice: I18n.t('tips.update.error')
    end
  end

  def destroy
    authorize! :destroy, @tip
    @tip.destroy
    redirect_to tips_url, notice: I18n.t('tips.destroy.success')
  end

  private

  def set_game
    @game = Game.find(params[:game_id])
    authorize! :read, @game
  end

  def set_participant
    @participant = Participant.find(params[:participant_id])
    authorize! :update, @participant
  end

  def set_tip
    @tip = Tip.find(params[:id])
  end

  def tip_params
    params.require(:tip).permit(:match_id, :home_goals, :away_goals)
  end
end

app/helpers/tips_helper.rb
# frozen_string_literal: true

module TipsHelper
  def tip_class(tip)
    if tip.earned_points == tip.game.rule_match
      5
    elsif tip.earned_points == tip.game.rule_goal_difference
      3
    elsif tip.earned_points == tip.game.rule_tendency
      2
    end
  end
end

app/views/tips/_form.html.haml
= simple_form_for tip, url: (tip.id ? game_participant_tip_url(game_id: game.to_param, participant_id: participant.to_param, id: tip.to_param) : game_participant_tips_url(game_id: game.to_param, participant_id: participant.to_param)) do |f|
  = f.input :match_id, as: :hidden, input_html: { value: tip.match_id }

  .match-wrapper
    = component 'flag', nation: tip.match.home
    .tip-wrapper
      = component 'myg/form-field', as: :input, attribute: :home_goals, class_name: 'tip', input_html: { required: true, type: :number, minlength: 1, maxlength: 1, placeholder: '-', size: 1, value: tip.home_goals, autofocus: true }
      %h1= ':'
      = component 'myg/form-field', as: :input, attribute: :away_goals, class_name: 'tip', input_html: { required: true, type: :number, minlength: 1, maxlength: 1, placeholder: '-', size: 1, value: tip.away_goals }
    = component 'flag', nation: tip.match.away

  .myg-button__container.myg-grid__flex.-reverse
    = component 'myg/button', value: t('d.continue'), class: 'myg-button--secondary'

app/views/tips/_tip.html.haml
- if tip.nil? && match.present? && game.present?
  = link_to (match.begins_at.past? ? 'javascript:void(0)' : new_game_participant_tip_url(game_id: game.to_param, participant_id: game.participants.find_by(user: current_user).to_param, match_id: match.to_param)), class: 'tip modalist--trigger', data: { turbolinks_animate_animation: 'fadeout' } do
    .myg-card
      .tip-wrapper
        %p.sm= match.home.name
        %h4= '? : ?'
        %p.sm= match.away.name
      .match-wrapper{ class: ('live' if match.live?) }
        = component 'flag', nation: match.home, size: 'tn'
        %p.sm
          = match.home_penalties || match.home_goals || '-'
          = ':'
          = match.away_penalties || match.away_goals || '-'
        = component 'flag', nation: match.away, size: 'tn'
      %p.sm= l(match.begins_at)
- elsif tip.present?
  = link_to (!can?(:update, tip) || tip.match.begins_at.past? ? 'javascript:void(0)' : edit_game_participant_tip_url(game_id: tip.participant.game.to_param, participant_id: tip.participant.to_param, id: tip.to_param)), class: 'tip modalist--trigger', data: { turbolinks_animate_animation: 'fadeout' } do
    .myg-card
      .tip-wrapper
        %p.sm= tip.match.home.name
        %h4= "#{tip.home_goals} : #{tip.away_goals}"
        %p.sm= tip.match.away.name
      .match-wrapper{ class: ('live' if tip.match.live?) }
        = component 'flag', nation: tip.match.home, size: 'tn'
        %p.sm
          = tip.match.home_penalties || tip.match.home_goals || '-'
          = ':'
          = tip.match.away_penalties || tip.match.away_goals || '-'
        = component 'flag', nation: tip.match.away, size: 'tn'
      %p.sm= l(tip.match.begins_at)

app/views/tips/edit.html.haml
= render 'form', tip: @tip, participant: @participant, game: @game

app/views/tips/index.html.haml
- meta title: t('tips.index.title', name: @game.name)

%h1= t('d.tips')

- if @matches_grouped_by_day.any?
  - @matches_grouped_by_day.each do |date, matches|
    %p= l(date)
    .myg-card__container
      - matches.each do |match|
        = render 'tip', tip: match.tips.includes(:participant).find_by(participants: { user: current_user, game: @game }), game: @game, match: match
- else
  %p= t('tips.index.none')

app/views/tips/new.html.haml
= render 'form', tip: @tip, participant: @participant, game: @game