config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invitations
  mount Pwa::Engine, at: ''

  constraints subdomain: '' do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
    resources :games, path: 'app', except: [:edit] do
      resources :invitations, only: [:show, :new, :create]
      resources :participants, except: [:edit, :update, :destroy] do
        resources :tips, except: [:show, :new, :edit]
        resources :tips, only: [:new, :edit], constraints: Modalist::Ajax.new
      end
      resources :matches, only: [:index, :show]
      resources :nations, only: [:show]
    end
    root to: 'welcome#index'
  end

  match '*path', to: 'r404#not_found', via: :all
end

app/helpers/layouts_helper.rb
# frozen_string_literal: true

module LayoutsHelper
  def body_class
    'myg myg-layout '\
    "#{class_hierarchy([params[:controller].split('/'), action_name])} "\
    "#{area(:body_class)}"
  end
end

app/views/layouts/app.html.haml
- replace :layout, 'app'
- if @game.participants.find_by(user: current_user)
  - replace :body_class, 'myg-layout--toolbar -bottom'

= mozaic do

  - if @game.participants.find_by(user: current_user)
    = component 'myg/toolbar', class: 'myg-toolbar--flexible -bottom', data: { turbolinks_animate_persist: 'nav' } do
      .mdc-toolbar__row
        = link_to game_url(id: @game.to_param), data: { turbolinks_animate_type: 'nav' } do
          %i.nc.nc-dashboard-29.nc-lg
          %p= t('d.dashboard')
        = link_to game_participants_url(game_id: @game.to_param), data: { turbolinks_animate_type: 'nav' } do
          %i.nc.nc-podium.nc-lg
          %p= t('d.leaderboard')
        = link_to game_matches_url(game_id: @game.to_param, anchor: Match.next&.id), data: { turbolinks_animate_type: 'nav' } do
          %i.nc.nc-soccer-field.nc-lg
          %p= t('d.matches')
        = link_to game_participant_tips_url(game_id: @game.to_param, participant_id: @game.participants.find_by(user: current_user).to_param), data: { turbolinks_animate_type: 'nav' } do
          %i.nc.nc-ball-soccer.nc-lg
          %p= t('d.tips')

  .myg-content
    = mozaic_area :app do
      = yield

app/views/layouts/application.html.haml
- replace :layout, 'application'

= mozaic do
  .myg-content
    = mozaic_area :application do
      = yield

app/views/layouts/back.html.haml
- replace :layout, 'back'
- replace :body_class, 'myg-layout--toolbar'

= mozaic do

  = component 'myg/toolbar' do
    .mdc-toolbar__row
      = link_to area(:back_location, url_for(:back)), data: { turbolinks_animate_appear: 'fadein' } do
        %i.nc.nc-tail-left-2.nc-lg

  .myg-content
    = mozaic_area :back do
      = yield

app/views/layouts/mozaic.html.haml
!!!
%html{ lang: I18n.locale }

  %head

    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1' }

    = metamagic site: t('layouts.mozaic.title'), title: [:title, :site], separator: ' - ', description: t('layouts.mozaic.description'), keywords: ['fifa', 'world cup', '2018']
    = component 'pwa/manifest', url: request.base_url

    %link{ rel: 'apple-touch-icon', sizes: '76x76', href: request.base_url + '/icon_76x76.png' }
    %link{ rel: 'apple-touch-icon', sizes: '120x120', href: request.base_url + '/icon_120x120.png' }
    %link{ rel: 'apple-touch-icon', sizes: '152x152', href: request.base_url + '/icon_152x152.png' }
    %link{ rel: 'icon', sizes: '192x192', href: request.base_url + '/icon_192x192.png' }
    %link{ rel: 'icon', sizes: '256x256', href: request.base_url + '/icon_256x256.png' }
    %link{ rel: 'icon', sizes: '384x384', href: request.base_url + '/icon_384x384.png' }
    %link{ rel: 'icon', sizes: '512x512', href: request.base_url + '/icon_512x512.png' }
    %link{ rel: 'msapplication-square70x70logo', content: request.base_url + '/icon_70x70.png' }
    %link{ rel: 'msapplication-square150x150logo', content: request.base_url + '/icon_150x150.png' }
    -# %link{ rel: 'msapplication-wide310x150logo', content: request.base_url + '/icon_310x150.png' }
    %link{ rel: 'msapplication-square310x310logo', content: request.base_url + '/icon_310x310.png' }

    = favicon_link_tag '/favicon.ico'
    = component 'pwa/theme', default: '#28c161'

    = component 'seo/schema', type: :brand, name: t('layouts.mozaic.title'), description: t('layouts.mozaic.description'), url: 'https://tip-the-world-cup.com', logo: 'https://tip-the-world-cup.com/icon_512x512.png'

    = stylesheet_pack_tag 'webpack', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'webpack', 'data-turbolinks-track': 'reload'

    = csrf_meta_tags

  = component 'turbolinks-animate', animation: @turbolinks_animate_animation, class: body_class, id: area(:layout) do

    %p.myg--hidden#notice= notice
    %p.myg--hidden#alert= alert
    = component 'myg/toast'

    = component 'modalist/overlay'
    = component 'modalist/wrapper'

    = component 'mobile'

    = mozaic_area do
      = yield